const actionTypes={
     SET_LOGIN_PENDING : 'SET_LOGIN_PENDING',
     SET_LOGIN_SUCCESS : 'SET_LOGIN_SUCCESS',
     SET_LOGIN_ERROR : 'SET_LOGIN_ERROR',
     REGISTERUSER:'REGISTERUSER'
}

export default actionTypes;